
/*

  KLayout Layout Viewer
  Copyright (C) 2006-2016 Matthias Koefferlein

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/

/**
*  @file generated/gsiDeclQProgressDialog_EventAdaptor.h
*  @brief Event adaptor implementations for QProgressDialog
*
*  DO NOT EDIT THIS FILE. 
*  This file has been created automatically
*/

#ifndef _HDR_gsiDeclQProgressDialog_EventAdaptor
#define _HDR_gsiDeclQProgressDialog_EventAdaptor

#include "gsiDecl.h"
#include "gsiQtEvents.h"
#include "gsiQtGui.h"
#include "gsiDeclQProgressDialog_Enums.h"

#include "layExceptions.h"

#include <QtCore/QObject>

// -----------------------------------------------------------------------
// class QProgressDialog_EventAdaptor

class QProgressDialog_EventAdaptor
  : public QObject, public qt_gsi::EventAdaptorBase, public gsi::ObjectBase
{
Q_OBJECT

public:
  QProgressDialog_EventAdaptor (QObject *host);

public slots:
  void accepted();
  void canceled();
  void customContextMenuRequested(const QPoint &);
  void destroyed(QObject *);
  void finished(int);
  void rejected();

public:
  gsi::event<> accepted_e_0;
  gsi::event<> canceled_e_0;
  gsi::event<const QPoint &> customContextMenuRequested_e_1916;
  gsi::event<QObject *> destroyed_e_1302;
  gsi::event<int> finished_e_767;
  gsi::event<> rejected_e_0;
};

#endif
