
/*

  KLayout Layout Viewer
  Copyright (C) 2006-2016 Matthias Koefferlein

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/

/**
*  @file gsiDeclQTextCodec_Enums.h 
*
*  DO NOT EDIT THIS FILE. 
*  This file has been created automatically
*/

#ifndef _HDR_gsiDeclQTextCodec_Enums
#define _HDR_gsiDeclQTextCodec_Enums

#include <QtCore/QFlags>

namespace qt_gsi
{

//  Wrapper class for QFlags<enum QTextCodec::ConversionFlag>
class QTextCodec_ConversionFlag_Enums : public QFlags<enum QTextCodec::ConversionFlag> {
public:
  QTextCodec_ConversionFlag_Enums () : m_flags () { }
  QTextCodec_ConversionFlag_Enums (enum QTextCodec::ConversionFlag v) : m_flags (v) { }
  QTextCodec_ConversionFlag_Enums (const QFlags<enum QTextCodec::ConversionFlag> &v) : m_flags (v) { }
  QFlags<enum QTextCodec::ConversionFlag> flags () const { return m_flags; }
private:
  QFlags<QTextCodec::ConversionFlag> m_flags;
};

//  Wrapper class for enum QTextCodec::ConversionFlag
class QTextCodec_ConversionFlag_Enum : public QTextCodec_ConversionFlag_Enums {
public:
  QTextCodec_ConversionFlag_Enum () { }
  QTextCodec_ConversionFlag_Enum (enum QTextCodec::ConversionFlag v) : QTextCodec_ConversionFlag_Enums (v) { }
  enum QTextCodec::ConversionFlag value () const { return (enum QTextCodec::ConversionFlag) flags ().operator int (); }
};

//  Converter for QFlags<enum QTextCodec::ConversionFlag>
template <>
struct Converter<QFlags<enum QTextCodec::ConversionFlag> >
{
public:
  typedef QFlags<enum QTextCodec::ConversionFlag> source_type;
  typedef QTextCodec_ConversionFlag_Enums target_type;
  static source_type toq (const target_type &c) { return c.flags (); }
  static target_type toc (const source_type &qc) { return target_type (qc); }
};

//  Converter for enum QTextCodec::ConversionFlag
template <>
struct Converter<enum QTextCodec::ConversionFlag>
{
public:
  typedef enum QTextCodec::ConversionFlag source_type;
  typedef QTextCodec_ConversionFlag_Enum target_type;
  static source_type toq (const target_type &c) { return c.value (); }
  static target_type toc (const source_type &qc) { return target_type (qc); }
};

}

#endif
