
/*

  KLayout Layout Viewer
  Copyright (C) 2006-2016 Matthias Koefferlein

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/

/**
*  @file gsiDeclQTextBlock_Iterator.cc 
*
*  DO NOT EDIT THIS FILE. 
*  This file has been created automatically
*/

#include "gsiQtGui.h"
#include "gsiDeclQtTypeTraits.h"
#include "gsiDeclQTextBlock_Iterator_Enums.h"
#include <memory>

// -----------------------------------------------------------------------
// class QTextBlock::iterator

//  Constructor QTextBlock::iterator::iterator()


static void _init_ctor_QTextBlock_Iterator_0 (qt_gsi::GenericStaticMethod *decl)
{
  decl->set_return_new<QTextBlock::iterator *> ();
}

static void _call_ctor_QTextBlock_Iterator_0 (const qt_gsi::GenericStaticMethod *decl, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  ret.write<QTextBlock::iterator *> (new QTextBlock::iterator ());
}

static qt_gsi::GenericStaticMethod *_create_ctor_QTextBlock_Iterator_0 ()
{
  return new qt_gsi::GenericStaticMethod ("new", "@brief Constructor QTextBlock::iterator::iterator()\nThis method creates an object of class QTextBlock::iterator.", &_init_ctor_QTextBlock_Iterator_0, &_call_ctor_QTextBlock_Iterator_0);
}

//  Constructor QTextBlock::iterator::iterator(const QTextBlock::iterator &o)


static void _init_ctor_QTextBlock_Iterator_3296 (qt_gsi::GenericStaticMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("o");
  decl->add_arg<const QTextBlock::iterator & > (argspec_0);
  decl->set_return_new<QTextBlock::iterator *> ();
}

static void _call_ctor_QTextBlock_Iterator_3296 (const qt_gsi::GenericStaticMethod *decl, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  const QTextBlock::iterator &arg1 = args.read<const QTextBlock::iterator & > ();
  ret.write<QTextBlock::iterator *> (new QTextBlock::iterator (arg1));
}

static qt_gsi::GenericStaticMethod *_create_ctor_QTextBlock_Iterator_3296 ()
{
  return new qt_gsi::GenericStaticMethod ("new", "@brief Constructor QTextBlock::iterator::iterator(const QTextBlock::iterator &o)\nThis method creates an object of class QTextBlock::iterator.", &_init_ctor_QTextBlock_Iterator_3296, &_call_ctor_QTextBlock_Iterator_3296);
}

// bool QTextBlock::iterator::atEnd()


static void _init_f_atEnd_c0 (qt_gsi::GenericMethod *decl)
{
  decl->set_return<bool > ();
}

static void _call_f_atEnd_c0 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  ret.write<bool > ((bool)((QTextBlock::iterator *)cls)->atEnd ());
}

static qt_gsi::GenericMethod *_create_f_atEnd_c0 ()
{
  return new qt_gsi::GenericMethod ("atEnd", "@brief Method bool QTextBlock::iterator::atEnd()\n", true, &_init_f_atEnd_c0, &_call_f_atEnd_c0);
}

// QTextFragment QTextBlock::iterator::fragment()


static void _init_f_fragment_c0 (qt_gsi::GenericMethod *decl)
{
  decl->set_return<QTextFragment > ();
}

static void _call_f_fragment_c0 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  ret.write<QTextFragment > ((QTextFragment)((QTextBlock::iterator *)cls)->fragment ());
}

static qt_gsi::GenericMethod *_create_f_fragment_c0 ()
{
  return new qt_gsi::GenericMethod ("fragment", "@brief Method QTextFragment QTextBlock::iterator::fragment()\n", true, &_init_f_fragment_c0, &_call_f_fragment_c0);
}

// bool QTextBlock::iterator::operator!=(const QTextBlock::iterator &o)


static void _init_f_operator_excl__eq__c3296 (qt_gsi::GenericMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("o");
  decl->add_arg<const QTextBlock::iterator & > (argspec_0);
  decl->set_return<bool > ();
}

static void _call_f_operator_excl__eq__c3296 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  const QTextBlock::iterator &arg1 = args.read<const QTextBlock::iterator & > ();
  ret.write<bool > ((bool)((QTextBlock::iterator *)cls)->operator!= (arg1));
}

static qt_gsi::GenericMethod *_create_f_operator_excl__eq__c3296 ()
{
  return new qt_gsi::GenericMethod ("!=", "@brief Method bool QTextBlock::iterator::operator!=(const QTextBlock::iterator &o)\n", true, &_init_f_operator_excl__eq__c3296, &_call_f_operator_excl__eq__c3296);
}

// QTextBlock::iterator &QTextBlock::iterator::operator++()


static void _init_f_operator_plus__plus__0 (qt_gsi::GenericMethod *decl)
{
  decl->set_return<QTextBlock::iterator & > ();
}

static void _call_f_operator_plus__plus__0 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  ret.write<QTextBlock::iterator & > ((QTextBlock::iterator &)((QTextBlock::iterator *)cls)->operator++ ());
}

static qt_gsi::GenericMethod *_create_f_operator_plus__plus__0 ()
{
  return new qt_gsi::GenericMethod ("++", "@brief Method QTextBlock::iterator &QTextBlock::iterator::operator++()\n", false, &_init_f_operator_plus__plus__0, &_call_f_operator_plus__plus__0);
}

// QTextBlock::iterator QTextBlock::iterator::operator++(int)


static void _init_f_operator_plus__plus__767 (qt_gsi::GenericMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("arg1");
  decl->add_arg<int > (argspec_0);
  decl->set_return<QTextBlock::iterator > ();
}

static void _call_f_operator_plus__plus__767 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  int arg1 = args.read<int > ();
  ret.write<QTextBlock::iterator > ((QTextBlock::iterator)((QTextBlock::iterator *)cls)->operator++ (arg1));
}

static qt_gsi::GenericMethod *_create_f_operator_plus__plus__767 ()
{
  return new qt_gsi::GenericMethod ("++", "@brief Method QTextBlock::iterator QTextBlock::iterator::operator++(int)\n", false, &_init_f_operator_plus__plus__767, &_call_f_operator_plus__plus__767);
}

// QTextBlock::iterator &QTextBlock::iterator::operator--()


static void _init_f_operator_minus__minus__0 (qt_gsi::GenericMethod *decl)
{
  decl->set_return<QTextBlock::iterator & > ();
}

static void _call_f_operator_minus__minus__0 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  ret.write<QTextBlock::iterator & > ((QTextBlock::iterator &)((QTextBlock::iterator *)cls)->operator-- ());
}

static qt_gsi::GenericMethod *_create_f_operator_minus__minus__0 ()
{
  return new qt_gsi::GenericMethod ("--", "@brief Method QTextBlock::iterator &QTextBlock::iterator::operator--()\n", false, &_init_f_operator_minus__minus__0, &_call_f_operator_minus__minus__0);
}

// QTextBlock::iterator QTextBlock::iterator::operator--(int)


static void _init_f_operator_minus__minus__767 (qt_gsi::GenericMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("arg1");
  decl->add_arg<int > (argspec_0);
  decl->set_return<QTextBlock::iterator > ();
}

static void _call_f_operator_minus__minus__767 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  int arg1 = args.read<int > ();
  ret.write<QTextBlock::iterator > ((QTextBlock::iterator)((QTextBlock::iterator *)cls)->operator-- (arg1));
}

static qt_gsi::GenericMethod *_create_f_operator_minus__minus__767 ()
{
  return new qt_gsi::GenericMethod ("--", "@brief Method QTextBlock::iterator QTextBlock::iterator::operator--(int)\n", false, &_init_f_operator_minus__minus__767, &_call_f_operator_minus__minus__767);
}

// bool QTextBlock::iterator::operator==(const QTextBlock::iterator &o)


static void _init_f_operator_eq__eq__c3296 (qt_gsi::GenericMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("o");
  decl->add_arg<const QTextBlock::iterator & > (argspec_0);
  decl->set_return<bool > ();
}

static void _call_f_operator_eq__eq__c3296 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  const QTextBlock::iterator &arg1 = args.read<const QTextBlock::iterator & > ();
  ret.write<bool > ((bool)((QTextBlock::iterator *)cls)->operator== (arg1));
}

static qt_gsi::GenericMethod *_create_f_operator_eq__eq__c3296 ()
{
  return new qt_gsi::GenericMethod ("==", "@brief Method bool QTextBlock::iterator::operator==(const QTextBlock::iterator &o)\n", true, &_init_f_operator_eq__eq__c3296, &_call_f_operator_eq__eq__c3296);
}


namespace gsi
{
gsi::Class<QTextBlock::iterator> decl_QTextBlock_Iterator ("QTextBlock_Iterator",
  gsi::Methods(_create_ctor_QTextBlock_Iterator_0 ()) +
  gsi::Methods(_create_ctor_QTextBlock_Iterator_3296 ()) +
  gsi::Methods(_create_f_atEnd_c0 ()) +
  gsi::Methods(_create_f_fragment_c0 ()) +
  gsi::Methods(_create_f_operator_excl__eq__c3296 ()) +
  gsi::Methods(_create_f_operator_plus__plus__0 ()) +
  gsi::Methods(_create_f_operator_plus__plus__767 ()) +
  gsi::Methods(_create_f_operator_minus__minus__0 ()) +
  gsi::Methods(_create_f_operator_minus__minus__767 ()) +
  gsi::Methods(_create_f_operator_eq__eq__c3296 ()),
  "@qt\n@brief Binding of QTextBlock::iterator");

gsi::ClassExt<QTextBlock> decl_QTextBlock_Iterator_as_child (decl_QTextBlock_Iterator, "Iterator");
}

