
/*

  KLayout Layout Viewer
  Copyright (C) 2006-2016 Matthias Koefferlein

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/

/**
*  @file gsiDeclQGraphicsSceneHoverEvent.cc 
*
*  DO NOT EDIT THIS FILE. 
*  This file has been created automatically
*/

#include "gsiQtGui.h"
#include "gsiDeclQtTypeTraits.h"
#include "gsiDeclQGraphicsSceneHoverEvent_Enums.h"
#include <memory>

// -----------------------------------------------------------------------
// class QGraphicsSceneHoverEvent

// QPointF QGraphicsSceneHoverEvent::lastPos()


static void _init_f_lastPos_c0 (qt_gsi::GenericMethod *decl)
{
  decl->set_return<QPointF > ();
}

static void _call_f_lastPos_c0 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  ret.write<QPointF > ((QPointF)((QGraphicsSceneHoverEvent *)cls)->lastPos ());
}

static qt_gsi::GenericMethod *_create_f_lastPos_c0 ()
{
  return new qt_gsi::GenericMethod (":lastPos", "@brief Method QPointF QGraphicsSceneHoverEvent::lastPos()\n", true, &_init_f_lastPos_c0, &_call_f_lastPos_c0);
}

// QPointF QGraphicsSceneHoverEvent::lastScenePos()


static void _init_f_lastScenePos_c0 (qt_gsi::GenericMethod *decl)
{
  decl->set_return<QPointF > ();
}

static void _call_f_lastScenePos_c0 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  ret.write<QPointF > ((QPointF)((QGraphicsSceneHoverEvent *)cls)->lastScenePos ());
}

static qt_gsi::GenericMethod *_create_f_lastScenePos_c0 ()
{
  return new qt_gsi::GenericMethod (":lastScenePos", "@brief Method QPointF QGraphicsSceneHoverEvent::lastScenePos()\n", true, &_init_f_lastScenePos_c0, &_call_f_lastScenePos_c0);
}

// QPoint QGraphicsSceneHoverEvent::lastScreenPos()


static void _init_f_lastScreenPos_c0 (qt_gsi::GenericMethod *decl)
{
  decl->set_return<QPoint > ();
}

static void _call_f_lastScreenPos_c0 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  ret.write<QPoint > ((QPoint)((QGraphicsSceneHoverEvent *)cls)->lastScreenPos ());
}

static qt_gsi::GenericMethod *_create_f_lastScreenPos_c0 ()
{
  return new qt_gsi::GenericMethod (":lastScreenPos", "@brief Method QPoint QGraphicsSceneHoverEvent::lastScreenPos()\n", true, &_init_f_lastScreenPos_c0, &_call_f_lastScreenPos_c0);
}

// QFlags<Qt::KeyboardModifier> QGraphicsSceneHoverEvent::modifiers()


static void _init_f_modifiers_c0 (qt_gsi::GenericMethod *decl)
{
  decl->set_return<qt_gsi::Converter<QFlags<Qt::KeyboardModifier> >::target_type > ();
}

static void _call_f_modifiers_c0 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  ret.write<qt_gsi::Converter<QFlags<Qt::KeyboardModifier> >::target_type > ((qt_gsi::Converter<QFlags<Qt::KeyboardModifier> >::target_type)qt_gsi::CppToQtAdaptor<QFlags<Qt::KeyboardModifier> >(((QGraphicsSceneHoverEvent *)cls)->modifiers ()));
}

static qt_gsi::GenericMethod *_create_f_modifiers_c0 ()
{
  return new qt_gsi::GenericMethod (":modifiers", "@brief Method QFlags<Qt::KeyboardModifier> QGraphicsSceneHoverEvent::modifiers()\n", true, &_init_f_modifiers_c0, &_call_f_modifiers_c0);
}

// QPointF QGraphicsSceneHoverEvent::pos()


static void _init_f_pos_c0 (qt_gsi::GenericMethod *decl)
{
  decl->set_return<QPointF > ();
}

static void _call_f_pos_c0 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  ret.write<QPointF > ((QPointF)((QGraphicsSceneHoverEvent *)cls)->pos ());
}

static qt_gsi::GenericMethod *_create_f_pos_c0 ()
{
  return new qt_gsi::GenericMethod (":pos", "@brief Method QPointF QGraphicsSceneHoverEvent::pos()\n", true, &_init_f_pos_c0, &_call_f_pos_c0);
}

// QPointF QGraphicsSceneHoverEvent::scenePos()


static void _init_f_scenePos_c0 (qt_gsi::GenericMethod *decl)
{
  decl->set_return<QPointF > ();
}

static void _call_f_scenePos_c0 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  ret.write<QPointF > ((QPointF)((QGraphicsSceneHoverEvent *)cls)->scenePos ());
}

static qt_gsi::GenericMethod *_create_f_scenePos_c0 ()
{
  return new qt_gsi::GenericMethod (":scenePos", "@brief Method QPointF QGraphicsSceneHoverEvent::scenePos()\n", true, &_init_f_scenePos_c0, &_call_f_scenePos_c0);
}

// QPoint QGraphicsSceneHoverEvent::screenPos()


static void _init_f_screenPos_c0 (qt_gsi::GenericMethod *decl)
{
  decl->set_return<QPoint > ();
}

static void _call_f_screenPos_c0 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  ret.write<QPoint > ((QPoint)((QGraphicsSceneHoverEvent *)cls)->screenPos ());
}

static qt_gsi::GenericMethod *_create_f_screenPos_c0 ()
{
  return new qt_gsi::GenericMethod (":screenPos", "@brief Method QPoint QGraphicsSceneHoverEvent::screenPos()\n", true, &_init_f_screenPos_c0, &_call_f_screenPos_c0);
}

// void QGraphicsSceneHoverEvent::setLastPos(const QPointF &pos)


static void _init_f_setLastPos_1986 (qt_gsi::GenericMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("pos");
  decl->add_arg<const QPointF & > (argspec_0);
  decl->set_return<void > ();
}

static void _call_f_setLastPos_1986 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  const QPointF &arg1 = args.read<const QPointF & > ();
  ((QGraphicsSceneHoverEvent *)cls)->setLastPos (arg1);
}

static qt_gsi::GenericMethod *_create_f_setLastPos_1986 ()
{
  return new qt_gsi::GenericMethod ("setLastPos|lastPos=", "@brief Method void QGraphicsSceneHoverEvent::setLastPos(const QPointF &pos)\n", false, &_init_f_setLastPos_1986, &_call_f_setLastPos_1986);
}

// void QGraphicsSceneHoverEvent::setLastScenePos(const QPointF &pos)


static void _init_f_setLastScenePos_1986 (qt_gsi::GenericMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("pos");
  decl->add_arg<const QPointF & > (argspec_0);
  decl->set_return<void > ();
}

static void _call_f_setLastScenePos_1986 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  const QPointF &arg1 = args.read<const QPointF & > ();
  ((QGraphicsSceneHoverEvent *)cls)->setLastScenePos (arg1);
}

static qt_gsi::GenericMethod *_create_f_setLastScenePos_1986 ()
{
  return new qt_gsi::GenericMethod ("setLastScenePos|lastScenePos=", "@brief Method void QGraphicsSceneHoverEvent::setLastScenePos(const QPointF &pos)\n", false, &_init_f_setLastScenePos_1986, &_call_f_setLastScenePos_1986);
}

// void QGraphicsSceneHoverEvent::setLastScreenPos(const QPoint &pos)


static void _init_f_setLastScreenPos_1916 (qt_gsi::GenericMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("pos");
  decl->add_arg<const QPoint & > (argspec_0);
  decl->set_return<void > ();
}

static void _call_f_setLastScreenPos_1916 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  const QPoint &arg1 = args.read<const QPoint & > ();
  ((QGraphicsSceneHoverEvent *)cls)->setLastScreenPos (arg1);
}

static qt_gsi::GenericMethod *_create_f_setLastScreenPos_1916 ()
{
  return new qt_gsi::GenericMethod ("setLastScreenPos|lastScreenPos=", "@brief Method void QGraphicsSceneHoverEvent::setLastScreenPos(const QPoint &pos)\n", false, &_init_f_setLastScreenPos_1916, &_call_f_setLastScreenPos_1916);
}

// void QGraphicsSceneHoverEvent::setModifiers(QFlags<Qt::KeyboardModifier> modifiers)


static void _init_f_setModifiers_3077 (qt_gsi::GenericMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("modifiers");
  decl->add_arg<const qt_gsi::Converter<QFlags<Qt::KeyboardModifier> >::target_type & > (argspec_0);
  decl->set_return<void > ();
}

static void _call_f_setModifiers_3077 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  const qt_gsi::Converter<QFlags<Qt::KeyboardModifier> >::target_type & arg1 = args.read<const qt_gsi::Converter<QFlags<Qt::KeyboardModifier> >::target_type & > ();
  ((QGraphicsSceneHoverEvent *)cls)->setModifiers (qt_gsi::QtToCppAdaptor<QFlags<Qt::KeyboardModifier> >(arg1).cref());
}

static qt_gsi::GenericMethod *_create_f_setModifiers_3077 ()
{
  return new qt_gsi::GenericMethod ("setModifiers|modifiers=", "@brief Method void QGraphicsSceneHoverEvent::setModifiers(QFlags<Qt::KeyboardModifier> modifiers)\n", false, &_init_f_setModifiers_3077, &_call_f_setModifiers_3077);
}

// void QGraphicsSceneHoverEvent::setPos(const QPointF &pos)


static void _init_f_setPos_1986 (qt_gsi::GenericMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("pos");
  decl->add_arg<const QPointF & > (argspec_0);
  decl->set_return<void > ();
}

static void _call_f_setPos_1986 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  const QPointF &arg1 = args.read<const QPointF & > ();
  ((QGraphicsSceneHoverEvent *)cls)->setPos (arg1);
}

static qt_gsi::GenericMethod *_create_f_setPos_1986 ()
{
  return new qt_gsi::GenericMethod ("setPos|pos=", "@brief Method void QGraphicsSceneHoverEvent::setPos(const QPointF &pos)\n", false, &_init_f_setPos_1986, &_call_f_setPos_1986);
}

// void QGraphicsSceneHoverEvent::setScenePos(const QPointF &pos)


static void _init_f_setScenePos_1986 (qt_gsi::GenericMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("pos");
  decl->add_arg<const QPointF & > (argspec_0);
  decl->set_return<void > ();
}

static void _call_f_setScenePos_1986 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  const QPointF &arg1 = args.read<const QPointF & > ();
  ((QGraphicsSceneHoverEvent *)cls)->setScenePos (arg1);
}

static qt_gsi::GenericMethod *_create_f_setScenePos_1986 ()
{
  return new qt_gsi::GenericMethod ("setScenePos|scenePos=", "@brief Method void QGraphicsSceneHoverEvent::setScenePos(const QPointF &pos)\n", false, &_init_f_setScenePos_1986, &_call_f_setScenePos_1986);
}

// void QGraphicsSceneHoverEvent::setScreenPos(const QPoint &pos)


static void _init_f_setScreenPos_1916 (qt_gsi::GenericMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("pos");
  decl->add_arg<const QPoint & > (argspec_0);
  decl->set_return<void > ();
}

static void _call_f_setScreenPos_1916 (const qt_gsi::GenericMethod *decl, void *cls, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  const QPoint &arg1 = args.read<const QPoint & > ();
  ((QGraphicsSceneHoverEvent *)cls)->setScreenPos (arg1);
}

static qt_gsi::GenericMethod *_create_f_setScreenPos_1916 ()
{
  return new qt_gsi::GenericMethod ("setScreenPos|screenPos=", "@brief Method void QGraphicsSceneHoverEvent::setScreenPos(const QPoint &pos)\n", false, &_init_f_setScreenPos_1916, &_call_f_setScreenPos_1916);
}

namespace gsi
{
extern gsi::Class<QGraphicsSceneEvent> decl_QGraphicsSceneEvent;

gsi::Class<QGraphicsSceneHoverEvent> decl_QGraphicsSceneHoverEvent (decl_QGraphicsSceneEvent, "QGraphicsSceneHoverEvent_Native",
  gsi::Methods(_create_f_lastPos_c0 ()) +
  gsi::Methods(_create_f_lastScenePos_c0 ()) +
  gsi::Methods(_create_f_lastScreenPos_c0 ()) +
  gsi::Methods(_create_f_modifiers_c0 ()) +
  gsi::Methods(_create_f_pos_c0 ()) +
  gsi::Methods(_create_f_scenePos_c0 ()) +
  gsi::Methods(_create_f_screenPos_c0 ()) +
  gsi::Methods(_create_f_setLastPos_1986 ()) +
  gsi::Methods(_create_f_setLastScenePos_1986 ()) +
  gsi::Methods(_create_f_setLastScreenPos_1916 ()) +
  gsi::Methods(_create_f_setModifiers_3077 ()) +
  gsi::Methods(_create_f_setPos_1986 ()) +
  gsi::Methods(_create_f_setScenePos_1986 ()) +
  gsi::Methods(_create_f_setScreenPos_1916 ()),
  "@hide\n@alias QGraphicsSceneHoverEvent");
}


class QGraphicsSceneHoverEvent_Adaptor : public QGraphicsSceneHoverEvent, public qt_gsi::QtObjectBase
{
public:

  virtual ~QGraphicsSceneHoverEvent_Adaptor();

  //  [adaptor ctor] QGraphicsSceneHoverEvent::QGraphicsSceneHoverEvent(QEvent::Type type)
  QGraphicsSceneHoverEvent_Adaptor() : QGraphicsSceneHoverEvent()
  {
    qt_gsi::QtObjectBase::init (this);
  }

  //  [adaptor ctor] QGraphicsSceneHoverEvent::QGraphicsSceneHoverEvent(QEvent::Type type)
  QGraphicsSceneHoverEvent_Adaptor(QEvent::Type type) : QGraphicsSceneHoverEvent(type)
  {
    qt_gsi::QtObjectBase::init (this);
  }

  
};

QGraphicsSceneHoverEvent_Adaptor::~QGraphicsSceneHoverEvent_Adaptor() { }

//  Constructor QGraphicsSceneHoverEvent::QGraphicsSceneHoverEvent(QEvent::Type type) (adaptor class)

static void _init_ctor_QGraphicsSceneHoverEvent_Adaptor_1565 (qt_gsi::GenericStaticMethod *decl)
{
  static gsi::ArgSpecBase argspec_0 ("type", true, "QEvent::None");
  decl->add_arg<const qt_gsi::Converter<QEvent::Type>::target_type & > (argspec_0);
  decl->set_return_new<QGraphicsSceneHoverEvent_Adaptor *> ();
}

static void _call_ctor_QGraphicsSceneHoverEvent_Adaptor_1565 (const qt_gsi::GenericStaticMethod *decl, gsi::SerialArgs &args, gsi::SerialArgs &ret) 
{
  tl::Heap heap;
  const qt_gsi::Converter<QEvent::Type>::target_type & arg1 = args ? args.read<const qt_gsi::Converter<QEvent::Type>::target_type & > () : (const qt_gsi::Converter<QEvent::Type>::target_type &)(qt_gsi::CppToQtReadAdaptor<QEvent::Type>(heap, QEvent::None));
  ret.write<QGraphicsSceneHoverEvent_Adaptor *> (new QGraphicsSceneHoverEvent_Adaptor (qt_gsi::QtToCppAdaptor<QEvent::Type>(arg1).cref()));
}

static qt_gsi::GenericStaticMethod *_create_ctor_QGraphicsSceneHoverEvent_Adaptor_1565 ()
{
  return new qt_gsi::GenericStaticMethod ("new", "@brief Constructor QGraphicsSceneHoverEvent::QGraphicsSceneHoverEvent(QEvent::Type type)\nThis method creates an object of class QGraphicsSceneHoverEvent.", &_init_ctor_QGraphicsSceneHoverEvent_Adaptor_1565, &_call_ctor_QGraphicsSceneHoverEvent_Adaptor_1565);
}

namespace gsi
{

extern gsi::Class<QGraphicsSceneHoverEvent> decl_QGraphicsSceneHoverEvent;

gsi::Class<QGraphicsSceneHoverEvent_Adaptor> decl_QGraphicsSceneHoverEvent_Adaptor (decl_QGraphicsSceneHoverEvent, "QGraphicsSceneHoverEvent",
  gsi::Methods(_create_ctor_QGraphicsSceneHoverEvent_Adaptor_1565 ()),
  "@qt\n@brief Binding of QGraphicsSceneHoverEvent");

}

