
/*

  KLayout Layout Viewer
  Copyright (C) 2006-2016 Matthias Koefferlein

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/

/**
*  @file gsiDeclQPolygon_Enums.h 
*
*  DO NOT EDIT THIS FILE. 
*  This file has been created automatically
*/

#ifndef _HDR_gsiDeclQPolygon_Enums
#define _HDR_gsiDeclQPolygon_Enums

#include <QtCore/QFlags>

namespace qt_gsi
{

//  Wrapper class for QFlags<enum Qt::FillRule>
class Qt_FillRule_Enums : public QFlags<enum Qt::FillRule> {
public:
  Qt_FillRule_Enums () : m_flags () { }
  Qt_FillRule_Enums (enum Qt::FillRule v) : m_flags (v) { }
  Qt_FillRule_Enums (const QFlags<enum Qt::FillRule> &v) : m_flags (v) { }
  QFlags<enum Qt::FillRule> flags () const { return m_flags; }
private:
  QFlags<Qt::FillRule> m_flags;
};

//  Wrapper class for enum Qt::FillRule
class Qt_FillRule_Enum : public Qt_FillRule_Enums {
public:
  Qt_FillRule_Enum () { }
  Qt_FillRule_Enum (enum Qt::FillRule v) : Qt_FillRule_Enums (v) { }
  enum Qt::FillRule value () const { return (enum Qt::FillRule) flags ().operator int (); }
};

//  Converter for QFlags<enum Qt::FillRule>
template <>
struct Converter<QFlags<enum Qt::FillRule> >
{
public:
  typedef QFlags<enum Qt::FillRule> source_type;
  typedef Qt_FillRule_Enums target_type;
  static source_type toq (const target_type &c) { return c.flags (); }
  static target_type toc (const source_type &qc) { return target_type (qc); }
};

//  Converter for enum Qt::FillRule
template <>
struct Converter<enum Qt::FillRule>
{
public:
  typedef enum Qt::FillRule source_type;
  typedef Qt_FillRule_Enum target_type;
  static source_type toq (const target_type &c) { return c.value (); }
  static target_type toc (const source_type &qc) { return target_type (qc); }
};

}

#endif
