
/*

  KLayout Layout Viewer
  Copyright (C) 2006-2016 Matthias Koefferlein

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/

/**
*  @file generated/gsiDeclQThread_EventAdaptor.cc
*  @brief Event adaptor implementations for QThread
*
*  DO NOT EDIT THIS FILE. 
*  This file has been created automatically
*/

#include "gsiQtCore.h"
#include "gsiDeclQThread_EventAdaptor.h"

// -----------------------------------------------------------------------
// class QThread_EventAdaptor

QThread_EventAdaptor::QThread_EventAdaptor (QObject *host)
  : QObject ()
{
  connect (host, SIGNAL(destroyed(QObject *)), this, SLOT(destroyed(QObject *)));
  connect (host, SIGNAL(finished()), this, SLOT(finished()));
  connect (host, SIGNAL(started()), this, SLOT(started()));
  connect (host, SIGNAL(terminated()), this, SLOT(terminated()));
}

//  Event QThread::destroyed(QObject *arg1)
void QThread_EventAdaptor::destroyed(QObject *arg1) {
BEGIN_PROTECTED
  destroyed_e_1302(arg1);
END_PROTECTED
}

//  Event QThread::finished()
void QThread_EventAdaptor::finished() {
BEGIN_PROTECTED
  finished_e_0();
END_PROTECTED
}

//  Event QThread::started()
void QThread_EventAdaptor::started() {
BEGIN_PROTECTED
  started_e_0();
END_PROTECTED
}

//  Event QThread::terminated()
void QThread_EventAdaptor::terminated() {
BEGIN_PROTECTED
  terminated_e_0();
END_PROTECTED
}
