
/*

  KLayout Layout Viewer
  Copyright (C) 2006-2016 Matthias Koefferlein

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/

/**
*  @file generated/gsiDeclQWidgetAction_EventAdaptor.cc
*  @brief Event adaptor implementations for QWidgetAction
*
*  DO NOT EDIT THIS FILE. 
*  This file has been created automatically
*/

#include "gsiQtGui.h"
#include "gsiDeclQWidgetAction_EventAdaptor.h"

// -----------------------------------------------------------------------
// class QWidgetAction_EventAdaptor

QWidgetAction_EventAdaptor::QWidgetAction_EventAdaptor (QObject *host)
  : QObject ()
{
  connect (host, SIGNAL(changed()), this, SLOT(changed()));
  connect (host, SIGNAL(destroyed(QObject *)), this, SLOT(destroyed(QObject *)));
  connect (host, SIGNAL(hovered()), this, SLOT(hovered()));
  connect (host, SIGNAL(toggled(bool)), this, SLOT(toggled(bool)));
  connect (host, SIGNAL(triggered(bool)), this, SLOT(triggered(bool)));
}

//  Event QWidgetAction::changed()
void QWidgetAction_EventAdaptor::changed() {
BEGIN_PROTECTED
  changed_e_0();
END_PROTECTED
}

//  Event QWidgetAction::destroyed(QObject *arg1)
void QWidgetAction_EventAdaptor::destroyed(QObject *arg1) {
BEGIN_PROTECTED
  destroyed_e_1302(arg1);
END_PROTECTED
}

//  Event QWidgetAction::hovered()
void QWidgetAction_EventAdaptor::hovered() {
BEGIN_PROTECTED
  hovered_e_0();
END_PROTECTED
}

//  Event QWidgetAction::toggled(bool arg1)
void QWidgetAction_EventAdaptor::toggled(bool arg1) {
BEGIN_PROTECTED
  toggled_e_864(arg1);
END_PROTECTED
}

//  Event QWidgetAction::triggered(bool checked)
void QWidgetAction_EventAdaptor::triggered(bool checked) {
BEGIN_PROTECTED
  triggered_e_864(checked);
END_PROTECTED
}
