
/*

  KLayout Layout Viewer
  Copyright (C) 2006-2016 Matthias Koefferlein

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

*/

/**
*  @file generated/gsiDeclQMdiSubWindow_EventAdaptor.cc
*  @brief Event adaptor implementations for QMdiSubWindow
*
*  DO NOT EDIT THIS FILE. 
*  This file has been created automatically
*/

#include "gsiQtGui.h"
#include "gsiDeclQMdiSubWindow_EventAdaptor.h"

// -----------------------------------------------------------------------
// class QMdiSubWindow_EventAdaptor

QMdiSubWindow_EventAdaptor::QMdiSubWindow_EventAdaptor (QObject *host)
  : QObject ()
{
  connect (host, SIGNAL(aboutToActivate()), this, SLOT(aboutToActivate()));
  connect (host, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(customContextMenuRequested(const QPoint &)));
  connect (host, SIGNAL(destroyed(QObject *)), this, SLOT(destroyed(QObject *)));
  connect (host, SIGNAL(windowStateChanged(QFlags<Qt::WindowState>, QFlags<Qt::WindowState>)), this, SLOT(windowStateChanged(QFlags<Qt::WindowState>, QFlags<Qt::WindowState>)));
}

//  Event QMdiSubWindow::aboutToActivate()
void QMdiSubWindow_EventAdaptor::aboutToActivate() {
BEGIN_PROTECTED
  aboutToActivate_e_0();
END_PROTECTED
}

//  Event QMdiSubWindow::customContextMenuRequested(const QPoint &pos)
void QMdiSubWindow_EventAdaptor::customContextMenuRequested(const QPoint &pos) {
BEGIN_PROTECTED
  customContextMenuRequested_e_1916(pos);
END_PROTECTED
}

//  Event QMdiSubWindow::destroyed(QObject *arg1)
void QMdiSubWindow_EventAdaptor::destroyed(QObject *arg1) {
BEGIN_PROTECTED
  destroyed_e_1302(arg1);
END_PROTECTED
}

//  Event QMdiSubWindow::windowStateChanged(QFlags<Qt::WindowState> oldState, QFlags<Qt::WindowState> newState)
void QMdiSubWindow_EventAdaptor::windowStateChanged(QFlags<Qt::WindowState> oldState, QFlags<Qt::WindowState> newState) {
BEGIN_PROTECTED
  windowStateChanged_e_5072(qt_gsi::CppToQtAdaptor<QFlags<Qt::WindowState> >(oldState), qt_gsi::CppToQtAdaptor<QFlags<Qt::WindowState> >(newState));
END_PROTECTED
}
