
vpath %.c $(SOURCE)/contrib/zlib
vpath %.h $(SOURCE)/contrib/zlib



SOURCES += \
  adler32.c \
  compress.c \
  crc32.c \
  deflate.c \
  gzclose.c \
  gzlib.c \
  gzread.c \
  gzwrite.c \
  infback.c \
  inffast.c \
  inflate.c \
  inftrees.c \
  trees.c \
  uncompr.c \
  zutil.c \

ifneq ($(HAVE_RUBY),0) 
SOURCES += \

endif

MOC_SOURCES += \

UI_SOURCES += \

RESOURCES += \

TESTS += \

